apiVersion: v1
kind: Service
metadata:
  name: overlord-hs
  namespace: druid
  labels:
    app: overlord
spec:
  ports:
  - port: 8091
    name: overlord
  clusterIP: None
  selector:
    app: overlord
---
apiVersion: v1
kind: Service
metadata:
  name: overlord-cs
  namespace: druid
  labels:
    app: overlord
spec:
  ports:
  - port: 8091
    name: overlord
  selector:
    app: overlord