apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi
  replicas: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchExpressions:
      #             - key: "app"
      #               operator: In
      #               values:
      #               - nifi
      #         topologyKey: "kubernetes.io/hostname"
      dnsConfig:
        searches:
          - "nifi.nifi.svc.cluster.local"
      containers:
      - name: nifi
        imagePullPolicy: Always
        image: "davideberdin/nifi:1.8.0"
        resources:
          requests:
            memory: 512m
            cpu: "0.2"
        ports:
          - containerPort: 8080
          - containerPort: 8081
          - containerPort: 8443
          - containerPort: 2882
        env:
        - name: IS_CLUSTER_NODE
          value: "true"
        - name: ELECTION_TIME
          value: "3 mins"
        - name: ZK_NODES_LIST
          value: "zk-0.zk-hs.druid.svc.cluster.local,zk-1.zk-hs.druid.svc.cluster.local,zk-2.zk-hs.druid.svc.cluster.local"
        - name: ZK_CONNECT_STRING
          value: "zk-0.zk-hs.druid.svc.cluster.local,zk-1.zk-hs.druid.svc.cluster.local,zk-2.zk-hs.druid.svc.cluster.local"
        volumeMounts:
          - name: "data"
            mountPath: /opt/nifi/data
          - name: "flowfile-repository"
            mountPath: /opt/nifi/flowfile_repository
          - name: "content-repository"
            mountPath: /opt/nifi/content_repository
          - name: "provenance-repository"
            mountPath: /opt/nifi/provenance_repository
          - name: "logs"
            mountPath: /opt/nifi/logs
  volumeClaimTemplates:
    - metadata:
        name: "data"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: "flowfile-repository"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: "content-repository"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: "provenance-repository"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: "logs"
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 5Gi
