apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coordinator
  namespace: druid
  labels:
    app: coordinator
spec:
  serviceName: coordinator
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: coordinator
        image: markthub/druid:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: coordinator
        resources:
          limits:
            cpu: "256m"
            memory: 256Mi
          requests:
            cpu: "256m"
            memory: 256Mi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: POSTGRES_URL
            value: "postgres-cs.druid.svc.cluster.local"
          - name: ZOOKEEPER_SERVER
            value: "zk-cs.druid.svc.cluster.local"
          - name: DRUID_SERVICE_PORT
            value: "8081"
          - name: DRUID_HOST
            value: "coordinator-cs.druid.svc.cluster.local"
          - name: DRUID_SERVICE
            value: "coordinator"
          - name: DRUID_JVM_ARGS
            value: "-server -Xms256m -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dderby.stream.error.file=var/druid/derby.log"
          - name: AWS_REGION
            value: eu-west-1
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_secret_key
          - name: BUCKET_STORAGE
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_storage
          - name: BUCKET_INDEX
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_index
      volumes:
      - name: druid-secret
        secret:
          secretName: druid-secret            