apiVersion: apps/v1
kind: Deployment
metadata:
  name: middlemanager
  namespace: druid
  labels:
    app: middlemanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middlemanager
  template:
    metadata:
      labels:
        app: middlemanager
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: middlemanager
        image: markthub/druid:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: middlemanager
        resources:
          limits:
            cpu: "512m"
            memory: 8Gi
          requests:
            cpu: "256m"
            memory: 4Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: POSTGRES_URL
            value: "postgres-cs.druid.svc.cluster.local"
          - name: ZOOKEEPER_SERVER
            value: "zk-cs.druid.svc.cluster.local"
          - name: DRUID_SERVICE_PORT
            value: "8084"
          - name: DRUID_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DRUID_SERVICE
            value: "middleManager"
          - name: DRUID_JVM_ARGS
            value: "-server -Xms4G -Xmx4G -XX:MaxDirectMemorySize=12G -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"
          - name: AWS_REGION
            value: eu-west-1
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_secret_key
          - name: BUCKET_STORAGE
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_storage
          - name: BUCKET_INDEX
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_index
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8084
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8084     
        volumeMounts:
        - mountPath: /var/druid/
          name: data
      volumes:
      - name: druid-secret
        secret:
          secretName: druid-secret
      - name: data
        emptyDir: {}